imports:
  - { resource: normalizers.yml }

services:
  api.param_converter.request_query_param_converter:
    class: ApiBundle\Request\ParamConverter\RequestQueryParamConverter
    arguments: ['@fos_rest.serializer', '@validator', 'constraintViolationList']
    tags:
      - { name: request.param_converter, converter: request_query_param_converter }

  api.view_type_normalizer_finder:
    class: ApiBundle\Service\ViewTypeNormalizerFinder