fos_rest:
  serializer:
    serialize_null: true
    #groups: [ 'Default' ]
    version: ~
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  #    routing_loader: true
  view:
    view_response_listener:
      enabled: true
      force: false
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: constraintViolationList # This is the default value
  exception:
    enabled: true
    codes:
      Symfony\Component\Security\Core\Exception\AuthenticationException: 401
      Symfony\Component\Security\Core\Exception\AccessDeniedException: 401
      Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: 401
      FOS\RestBundle\Exception\InvalidParameterException: 400
      Symfony\Component\HttpKernel\Exception\GoneHttpException: 410
      Symfony\Component\HttpKernel\Exception\ConflictHttpException: 409
      Symfony\Component\HttpKernel\Exception\LengthRequiredHttpException: 411
      Symfony\Component\HttpKernel\Exception\PreconditionFailedHttpException: 412
      Symfony\Component\HttpKernel\Exception\UnsupportedMediaTypeHttpException: 415
      Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException: 422
      Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException: 429
      Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException: 406
      Symfony\Component\HttpKernel\Exception\BadRequestHttpException: 400
      Symfony\Component\HttpKernel\Exception\NotFoundHttpException: 404
      Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException: 401
      Symfony\Component\Routing\Exception\ResourceNotFoundException: 404
      InvalidArgumentException: 400
    messages:
      Symfony\Component\Security\Core\Exception\AuthenticationException: true
      Symfony\Component\Security\Core\Exception\AccessDeniedException: true
      Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: true
      Symfony\Component\HttpKernel\Exception\HttpException: true
      FOS\RestBundle\Exception\InvalidParameterException: true
      Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException: true
      Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
      Symfony\Component\HttpKernel\Exception\NotFoundHttpException: true
      Symfony\Component\Routing\Exception\ResourceNotFoundException: true
      Symfony\Component\HttpKernel\Exception\GoneHttpException: true
      Symfony\Component\HttpKernel\Exception\ConflictHttpException: true
      Symfony\Component\HttpKernel\Exception\LengthRequiredHttpException: true
      Symfony\Component\HttpKernel\Exception\PreconditionFailedHttpException: true
      Symfony\Component\HttpKernel\Exception\UnsupportedMediaTypeHttpException: true
      Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException: true
      Symfony\Component\HttpKernel\Exception\TooManyRequestsHttpException: true
      Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException: true
      InvalidArgumentException: true
  #    exception:
  #        enabled: true
  #        codes:
  #            App\Exception\MyException: 403
  #        messages:
  #            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
      - { path: ^/, priorities: ['html', '*/*'], fallback_format: ~, prefer_extension: true }